Metrics/LineLength:
  Max: 500

Security/Eval:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4.1
  DisplayCopNames: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Metrics/BlockLength:
  Max: 80

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
