title: DIRCord
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Chew"
  email: "chew@chew.pw"
  url: "https://dircord.chew.pro/hacker-blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Chew"
year : "2019"
